

const Data = [
  { id: 1, question: "What is the difference between var, let, and const in JavaScript?", acceptance: "82%", difficulty: "Easy" },
  { id: 2, question: "Explain closures in JavaScript with an example.", acceptance: "67%", difficulty: "Medium" },
  { id: 3, question: "Write a function to check if a string is a palindrome.", acceptance: "74%", difficulty: "Easy" },
  { id: 4, question: "What is a callback function in JavaScript?", acceptance: "80%", difficulty: "Easy" },
  { id: 5, question: "Write a program to reverse a linked list.", acceptance: "45%", difficulty: "Hard" },
  { id: 6, question: "Explain the difference between == and === in JavaScript.", acceptance: "85%", difficulty: "Easy" },
  { id: 7, question: "Find the longest substring without repeating characters.", acceptance: "54%", difficulty: "Medium" },
  { id: 8, question: "What is memoization and how is it used in programming?", acceptance: "60%", difficulty: "Medium" },
  { id: 9, question: "Implement binary search in JavaScript.", acceptance: "70%", difficulty: "Medium" },
  { id: 10, question: "What is the difference between stack and queue?", acceptance: "77%", difficulty: "Easy" },
  { id: 11, question: "What are Promises and async/await in JavaScript?", acceptance: "68%", difficulty: "Medium" },
  { id: 12, question: "Write a function to check if a number is prime.", acceptance: "72%", difficulty: "Easy" },
  { id: 13, question: "Implement a basic debounce function in JavaScript.", acceptance: "59%", difficulty: "Medium" },
  { id: 14, question: "Solve the Tower of Hanoi problem.", acceptance: "40%", difficulty: "Hard" },
  { id: 15, question: "Find the nth Fibonacci number using recursion.", acceptance: "65%", difficulty: "Medium" },
  { id: 16, question: "What is the use of the `this` keyword in JavaScript?", acceptance: "66%", difficulty: "Medium" },
  { id: 17, question: "Detect a cycle in a linked list.", acceptance: "50%", difficulty: "Hard" },
  { id: 18, question: "Explain event bubbling and event capturing.", acceptance: "71%", difficulty: "Medium" },
  { id: 19, question: "Write a function to flatten a nested array.", acceptance: "63%", difficulty: "Medium" },
  { id: 20, question: "What is the difference between synchronous and asynchronous code?", acceptance: "78%", difficulty: "Easy" },
  { id: 21, question: "What is the difference between var, let, and const in JavaScript?", acceptance: "82%", difficulty: "Easy" },
  { id: 22, question: "Explain closures in JavaScript with an example.", acceptance: "67%", difficulty: "Medium" },
  { id: 23, question: "Write a function to check if a string is a palindrome.", acceptance: "74%", difficulty: "Easy" },
  { id: 24, question: "What is a callback function in JavaScript?", acceptance: "80%", difficulty: "Easy" },
  { id: 25, question: "Write a program to reverse a linked list.", acceptance: "45%", difficulty: "Hard" },
  { id: 26, question: "Explain the difference between == and === in JavaScript.", acceptance: "85%", difficulty: "Easy" },
  { id: 27, question: "Find the longest substring without repeating characters.", acceptance: "54%", difficulty: "Medium" },
  { id: 28, question: "What is memoization and how is it used in programming?", acceptance: "60%", difficulty: "Medium" },
  { id: 29, question: "Implement binary search in JavaScript.", acceptance: "70%", difficulty: "Medium" },
  { id: 30, question: "What is the difference between stack and queue?", acceptance: "77%", difficulty: "Easy" },
  { id:31, question: "What are Promises and async/await in JavaScript?", acceptance: "68%", difficulty: "Medium" },
  { id: 32, question: "Write a function to check if a number is prime.", acceptance: "72%", difficulty: "Easy" },
  { id: 33, question: "Implement a basic debounce function in JavaScript.", acceptance: "59%", difficulty: "Medium" },
  { id: 34, question: "Solve the Tower of Hanoi problem.", acceptance: "40%", difficulty: "Hard" },
  { id: 35, question: "Find the nth Fibonacci number using recursion.", acceptance: "65%", difficulty: "Medium" },
  { id: 36, question: "What is the use of the `this` keyword in JavaScript?", acceptance: "66%", difficulty: "Medium" },
  { id: 37, question: "Detect a cycle in a linked list.", acceptance: "50%", difficulty: "Hard" },
  { id: 38, question: "Explain event bubbling and event capturing.", acceptance: "71%", difficulty: "Medium" },
  { id: 39, question: "Write a function to flatten a nested array.", acceptance: "63%", difficulty: "Medium" },
  { id: 40, question: "What is the difference between synchronous and asynchronous code?", acceptance: "78%", difficulty: "Easy" }
];
 export default Data